(function(){
	//only used for poedit to find translatable strings
	var keywords = [ 
		_('saved.'),
		_('electricity'),
		_('builder'),
		_('power_supplies'),
		_('Lightning'),
		_('smart_contract'),
		_('mining_hardware'),
		_('hash_power_GPU'),
		_('charm'),
		_('wood_mining_frame'),
		_('iron_mining_frame'),
		_('steel_mining_frame'),
		_('ether'),
		_('PoW'),
		_('hash_power_ASIC'),
		_('watch_tower'),
		_('Bitcoin_culture'),
		_('Jameson Lopp'),
		_('Faketoshi'),
		_('Brian Armstrong'),
		_('hash_attack'),
		_('bolas'),
		_('GPU'),
		_('Saifedean Ammous'),
		_('iron miner'),
		_('iron mine'),
		_('ether miner'),
		_('ether mine'),
		_('PoW miner'),
		_('PoW mine'),
		_('armourer'),
		_('steelworker'),
		_('clickbait'),
		_('cured Lightning'),
		_('electric meter'),
		_('Bitcoin_Whitepaper'),
		_('ASIC'),
		_('gatherer'),
		_('chip'),
		_('electric meter'),
		_('cured Lightning'),
		_('thieves'),
		_('not enough smart_contract'),
		_('not enough electricity'),
		_('not enough ether'),
		_('not enough iron'),
		_('not enough steel'),
		_('not enough PoW'),
		_('clickbait trap'),
		_('not enough electric_meter'),
		_('not enough chip'),
		_('not enough smart_supply'),
		_('not enough mining_rig'),
		_('not enough Lightning'),
		_('the Bitcoin_Whitepaper points east'),
		_('the Bitcoin_Whitepaper points west'),
		_('the Bitcoin_Whitepaper points north'),
		_('the Bitcoin_Whitepaper points south'),
		_('the Bitcoin_Whitepaper points northeast'),
		_('the Bitcoin_Whitepaper points northwest'),
		_('the Bitcoin_Whitepaper points southeast'),
		_('the Bitcoin_Whitepaper points southwest')
	]; 

	keywords = null;
})();
