(function(){
	//only used for poedit to find translatable strings
	var keywords = [ 
		_('saved.'),
		_('electricity'),
		_('Hal Finney'),
		_('power_supplies'),
		_('Lightning'),
		_('smart_contract'),
		_('mining_hardware'),
		_('hash_power_1'),
		_('charm'),
		_('wood_mining_frame'),
		_('iron_mining_frame'),
		_('steel_mining_frame'),
		_('coal'),
		_('sulphur'),
		_('hash_power_2'),
		_('torch'),
		_('Bitcoin_culture'),
		_('hunter'),
		_('trapper'),
		_('tanner'),
		_('grenade'),
		_('bolas'),
		_('GPU'),
		_('charcutier'),
		_('iron miner'),
		_('iron mine'),
		_('coal miner'),
		_('coal mine'),
		_('sulphur miner'),
		_('sulphur mine'),
		_('armourer'),
		_('steelworker'),
		_('clickclickbait'),
		_('cured Lightning'),
		_('electric meter'),
		_('compass'),
		_('ASIC'),
		_('gatherer'),
		_('cloth'),
		_('electric meter'),
		_('cured Lightning'),
		_('thieves'),
		_('not enough smart_contract'),
		_('not enough electricity'),
		_('not enough coal'),
		_('not enough iron'),
		_('not enough steel'),
		_('not enough sulphur'),
		_('clickclickbaited trap'),
		_('not enough scales'),
		_('not enough cloth'),
		_('not enough smart_supply'),
		_('not enough mining_rig'),
		_('not enough Lightning'),
		_('the compass points east'),
		_('the compass points west'),
		_('the compass points north'),
		_('the compass points south'),
		_('the compass points northeast'),
		_('the compass points northwest'),
		_('the compass points southeast'),
		_('the compass points southwest')
	]; 

	keywords = null;
})();
